-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets


	o["wpn_rem700_aics"] = {
		y = 0.25,
		z = -0.075,
	}
	o["wpn_rem700_mcmillan"] = {
		y = 0.25,
		z = -0.075,
	}

end