-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets


	o["wpn_pkm_zenit_shorty"] = {
		y = 0.20,
		z = -0.05,
	}

	o["wpn_pkp_tac_siber"] = {
		y = 0.25,
		z = -0.075,
	}

end